apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: win-node-exporter
  name: win-node-exporter
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 9100
    protocol: TCP
    targetPort: https
  selector:
    app: win-node-exporter